services:
  se.plan:
    build:
      dockerfile: ./Dockerfile
      args:
        - GIT_COMMIT=${GIT_COMMIT:-""}
    image: "openforis/seplan"
    container_name: se.plan
    volumes:
      - "${EE_CREDENTIALS_PATH:-${HOME}/.config/earthengine/credentials}:/root/.config/earthengine/credentials"
    environment:
      SEPAL_HOST: "${SEPAL_HOST}"
      FORWARDED_ALLOW_IPS: "*"
      SOLARA_THEME_SHOW_BANNER: "False"
      SOLARA_TEST: "${SOLARA_TEST:-false}"
      LOCAL_SEPAL_USER: "${LOCAL_SEPAL_USER:-}"
      LOCAL_SEPAL_PASSWORD: "${LOCAL_SEPAL_PASSWORD:-}"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8765"]
      start_period: 60s
      start_interval: 1s
      interval: 20s
      timeout: 5s
      retries: 3
    networks:
      - sepal
    restart: always
    labels:
      org.opencontainers.image.source: https://github.com/sepal-contrib/se.plan

networks:
  sepal:
    external: true