version = 1
disable_existing_loggers = false

# ─── FORMATTERS ──────────────────────────────────────────────
[formatters.colored_seplan]
"()"      = "colorlog.ColoredFormatter"
format    = "%(log_color)s%(asctime)s - \u001b[44m%(name)s\u001b[0m - %(levelname)s - %(message)s"
datefmt   = "%Y-%m-%d %H:%M:%S"
[formatters.colored_seplan.log_colors]
DEBUG     = "cyan"
INFO      = "green"
WARNING   = "yellow"
ERROR     = "red"
CRITICAL  = "bold_red"

[formatters.colored_ee]
"()"      = "colorlog.ColoredFormatter"
format    = "%(log_color)s%(asctime)s - \u001b[45m%(name)s\u001b[0m - %(levelname)s - %(message)s"
datefmt   = "%Y-%m-%d %H:%M:%S"
[formatters.colored_ee.log_colors]
DEBUG     = "cyan"
INFO      = "white"
WARNING   = "yellow"
ERROR     = "red"
CRITICAL  = "bold_red"


# ─── HANDLERS ────────────────────────────────────────────────

[handlers.console]
class     = "logging.StreamHandler"
level     = "DEBUG"
stream    = "ext://sys.stdout"

[handlers.seplan_console]
class     = "logging.StreamHandler"
formatter = "colored_seplan"
stream    = "ext://sys.stdout"

[handlers.ee_console]
class     = "logging.StreamHandler"
formatter = "colored_ee"
stream    = "ext://sys.stdout"

# ─── LOGGERS ────────────────────────────────────────────────

[loggers.SEPLAN]
level     = "DEBUG"
handlers  = ["seplan_console"]
propagate = false

[loggers.eeclient]
level     = "INFO"
handlers  = ["ee_console"]
propagate = false

[loggers.httpx]
level     = "WARNING"
handlers  = ["console"]
propagate = false

[loggers."numexpr.utils"]
level     = "WARNING"
handlers  = ["console"]
propagate = false

# ─── ROOT ───────────────────────────────────────────────────
[root]
level    = "WARNING"
handlers = ["console"]
